language: php


matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=2.7.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*

env:
  global:
    - SYMFONY_VERSION=""

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/console "$SYMFONY_VERSION"; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/finder "$SYMFONY_VERSION"; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/process "$SYMFONY_VERSION"; fi

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --exclude-group functional

after_script:
  - vendor/bin/coveralls

notifications:
  email: matthiasnoback@gmail.com
