language: php


php:
  - 5.4

env:
  - SYMFONY_VERSION: 2.3.*
  - SYMFONY_VERSION: 2.4.*
  - SYMFONY_VERSION: 2.5.*
  - SYMFONY_VERSION: 2.6.*
  - SYMFONY_VERSION: 2.7.*@dev

before_install:
  - composer selfupdate
  - composer require --no-update symfony/http-kernel:${SYMFONY_VERSION} symfony/dependency-injection:${SYMFONY_VERSION} symfony/yaml:${SYMFONY_VERSION}

install:
  - composer update --prefer-dist

script:
  - vendor/bin/phpunit

notifications:
  email: matthiasnoback@gmail.com
