language: php

php:
  - 5.4

before_script:
  - composer selfupdate
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls

notifications:
  email: matthiasnoback@gmail.com
