services:
    simple_bus.rabbit_mq.command_publisher:
        class: SimpleBus\RabbitMQBundle\RabbitMQPublisher
        arguments:
            # defined by SimpleBusAsynchronousBundle
            - @simple_bus.asynchronous.message_serializer
            # defined in this bundle's configuration
            - @simple_bus.rabbit_mq.command_producer

    simple_bus.rabbit_mq.commands_consumer:
        class: SimpleBus\RabbitMQBundle\RabbitMQMessageConsumer
        arguments:
            # defined by SimpleBusAsynchronousBundle
            - @simple_bus.asynchronous.standard_serialized_command_envelope_consumer
            - @event_dispatcher
