services:
    simple_bus.asynchronous.command_publisher:
        alias: simple_bus.rabbit_mq.command_publisher

    simple_bus.rabbit_mq.command_publisher:
        class: SimpleBus\RabbitMQBundle\RabbitMQPublisher
        arguments:
            # defined by another bundle
            - @simple_bus.asynchronous.message_serializer
            # defined in this bundle's configuration
            - @simple_bus.rabbit_mq.command_producer

    simple_bus.rabbit_mq.commands_consumer:
        class: SimpleBus\RabbitMQBundle\RabbitMQMessageConsumer
        arguments:
            # defined by another bundle
            - @simple_bus.asynchronous.message_serializer
            # defined by SimpleBusCommandBusBundle
            - @asynchronous_command_bus
