services:
    simple_bus.asynchronous.event_publisher:
        alias: simple_bus.rabbit_mq.event_publisher

    simple_bus.rabbit_mq.event_publisher:
        class: SimpleBus\RabbitMQBundle\RabbitMQPublisher
        arguments:
            # defined by SimpleBusAsynchronousBundle
            - @simple_bus.asynchronous.message_serializer
            # defined in this bundle's configuration
            - @simple_bus.rabbit_mq.event_producer

    simple_bus.rabbit_mq.events_consumer:
        class: SimpleBus\RabbitMQBundle\RabbitMQMessageConsumer
        arguments:
            # defined by SimpleBusAsynchronousBundle
            - @simple_bus.asynchronous.standard_serialized_event_envelope_consumer
            - @event_dispatcher
