services:
    simple_bus.rabbit_mq.routing.class_based_routing_key_resolver:
        class: SimpleBus\RabbitMQBundle\Routing\ClassBasedRoutingKeyResolver
        public: false

    simple_bus.rabbit_mq.routing.empty_routing_key_resolver:
        class: SimpleBus\RabbitMQBundle\Routing\EmptyRoutingKeyResolver
        public: false
