services:
    simple_bus.asynchronous.envelope_factory:
        alias: simple_bus.asynchronous.default_envelope_factory

    simple_bus.asynchronous.default_envelope_factory:
        class: SimpleBus\Asynchronous\Message\Envelope\DefaultEnvelopeFactory
        public: false

    simple_bus.asynchronous.message_serializer:
        alias: simple_bus.asynchronous.standard_message_in_envelop_serializer

    simple_bus.asynchronous.standard_message_in_envelop_serializer:
        class: SimpleBus\Asynchronous\Message\Envelope\Serializer\StandardMessageInEnvelopeSerializer
        arguments:
            - @simple_bus.asynchronous.envelope_factory
            # configured inside the bundle configuration
            - @simple_bus.asynchronous.object_serializer
